from math import *
a = float(input())
print('целое число - ',a)
print('int -', int(a))
print('round -', round(a))
print('round x, 3 - ', round(a, 3))
print('floor - ', floor(a))
print('ceil - ', ceil(a))
print('abs -', abs(a))
print('sqrt -', sqrt(a))
print('pow -', pow(a, 2))
print('log - ', a)
print('Число e -', e)